---
version: "3"

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10.0
    environment:
      - POSTGRES_USER=origin
      - POSTGRES_PASSWORD=origin
      - POSTGRES_DB=origin

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    build:
      context: .
      dockerfile: development/dockerfiles/elasticsearch
    ports:
      - "9200:9200"
    environment:
      network.bind_host: 0
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: ganache-cli -h 0.0.0.0

  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"

  ipfs-proxy:
    container_name: ipfs-proxy
    image: ipfs-proxy
    build:
      context: .
      dockerfile: development/dockerfiles/ipfs-proxy
    ports:
      - "9999:9999"
    volumes:
      - ./ipfs-proxy/src:/app/src
    environment:
      - IPFS_API_URL=http://ipfs:5002
      - IPFS_GATEWAY_URL=http://ipfs:8080
    depends_on:
      - ipfs

  origin-bridge:
    container_name: origin-bridge
    image: origin-bridge
    build:
      context: .
      dockerfile: development/dockerfiles/origin-bridge
    volumes:
      - ./origin-bridge:/app
      # Set the envfile from the local envfile
      - ./development/envfiles/origin-bridge.env:/app/.env
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/app/main.py
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://origin:origin@postgres/origin

  origin-messaging:
    container_name: origin-messaging
    image: origin-messaging
    build:
      context: .
      dockerfile: development/dockerfiles/origin-messaging
    ports:
      - "9012:9012"
    volumes:
      - ./origin-messaging/src:/app/src
      - ./development/.ipfs:/ipfs

  origin:
    container_name: origin
    image: origin
    build:
      context: .
      dockerfile: development/dockerfiles/origin
    environment:
      - DATABASE_URL=postgres://origin:origin@postgres/origin
      - ELASTICSEARCH_HOST=elasticsearch:9200
    volumes:
      - ./origin-js/src:/app/origin-js/src
      - ./origin-discovery/src:/app/origin-discovery/src
      - ./origin-dapp/src:/app/origin-dapp/src
      - ./origin-dapp/translations:/app/origin-dapp/translations
      - ./origin-dapp/public:/app/origin-dapp/public
    ports:
      - "3000:3000"  # origin-dapp
      - "4000:4000"  # origin-discovery
    depends_on:
      - elasticsearch
      - ganache
      - origin-messaging
      - origin-bridge
      - ipfs-proxy
